const today = '2026-09-23T12:00:00-03:00';
const baseAnuncios = [
  { anuncio_id: 101, anuncio_portal_id: 'DEMO-001', titulo: 'Volvo FH 540 6x4 2021', tipo: 'caminhao', marca: 'Volvo', modelo: 'FH 540', ano_fabricacao: 2021, ano_modelo: 2021, preco: 489900, preco_fipe: 505000, codigo_fipe: 'E001-001', fipe_match_status: 'vinculado', fipe_match_confianca: 'alta', fipe_vinculo_origem: 'automatico', cidade: 'Curitiba', uf: 'PR', regiao: 'Sul', revenda_id: 11, revenda: 'Rota Exemplo Caminhoes', quilometragem: 312000, primeira_vez_visto: '2026-08-24', ultima_vez_ativo: today, anuncios_comparaveis: 11, preco_mediano_mercado: 498000, preco_p25_mercado: 475000, preco_p75_mercado: 520000, mercado_confianca: 'media', mercado_amostra_suficiente: 1, preco_qualidade_status: 'valido', status: 'ativo' },
  { anuncio_id: 102, anuncio_portal_id: 'DEMO-002', titulo: 'Scania R 450 2020', tipo: 'caminhao', marca: 'Scania', modelo: 'R 450', ano_fabricacao: 2020, ano_modelo: 2020, preco: 418000, preco_fipe: 431000, codigo_fipe: 'E002-002', fipe_match_status: 'vinculado', fipe_match_confianca: 'media', cidade: 'Campinas', uf: 'SP', regiao: 'Sudeste', revenda_id: 12, revenda: 'Patio Demonstracao', quilometragem: 365000, primeira_vez_visto: '2026-07-15', ultima_vez_ativo: today, anuncios_comparaveis: 9, preco_mediano_mercado: 425000, preco_p25_mercado: 401000, preco_p75_mercado: 449000, mercado_confianca: 'media', mercado_amostra_suficiente: 1, preco_qualidade_status: 'valido', status: 'ativo' },
  { anuncio_id: 103, anuncio_portal_id: 'DEMO-003', titulo: 'DAF XF 530 2022', tipo: 'caminhao', marca: 'DAF', modelo: 'XF 530', ano_fabricacao: 2022, ano_modelo: 2022, preco: 536000, preco_fipe: 521000, codigo_fipe: 'E003-003', fipe_match_status: 'vinculado', fipe_match_confianca: 'baixa', cidade: 'Londrina', uf: 'PR', regiao: 'Sul', revenda_id: 13, revenda: 'Caminhoes Modelo', quilometragem: 198000, primeira_vez_visto: '2026-08-01', ultima_vez_ativo: today, anuncios_comparaveis: 7, preco_mediano_mercado: 530000, mercado_confianca: 'baixa', mercado_amostra_suficiente: 1, preco_qualidade_status: 'valido', status: 'ativo' }
];
const ufs = { PR: { regiao: 'Sul', anuncios: 422, revendas: 18, cidades: [{ cidade: 'Curitiba', n: 322, uf: 'PR' }, { cidade: 'Londrina', n: 100, uf: 'PR' }], lojistas: [{ id: 11, nome: 'Rota Exemplo Caminhoes', n: 18 }] }, SP: { regiao: 'Sudeste', anuncios: 581, revendas: 15, cidades: [{ cidade: 'Campinas', n: 355, uf: 'SP' }, { cidade: 'Sao Paulo', n: 226, uf: 'SP' }], lojistas: [{ id: 12, nome: 'Patio Demonstracao', n: 14 }] }, SC: { regiao: 'Sul', anuncios: 281, revendas: 9, cidades: [{ cidade: 'Joinville', n: 126, uf: 'SC' }], lojistas: [] }, RS: { regiao: 'Sul', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, RJ: { regiao: 'Sudeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, MG: { regiao: 'Sudeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, ES: { regiao: 'Sudeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, MT: { regiao: 'Centro-Oeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, MS: { regiao: 'Centro-Oeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, GO: { regiao: 'Centro-Oeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, DF: { regiao: 'Centro-Oeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, BA: { regiao: 'Nordeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, PE: { regiao: 'Nordeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, CE: { regiao: 'Nordeste', anuncios: 0, revendas: 0, cidades: [], lojistas: [] }, AM: { regiao: 'Norte', anuncios: 0, revendas: 0, cidades: [], lojistas: [] } };
const facetas = { total_geral: 1284, ufs, por_uf: { PR: 422, SP: 581, SC: 281 }, revendas_por_uf: { PR: 18, SP: 15, SC: 9 }, regioes: { Sul: { anuncios: 703, revendas: 27 }, Sudeste: { anuncios: 581, revendas: 15 }, 'Centro-Oeste': { anuncios: 0, revendas: 0 }, Nordeste: { anuncios: 0, revendas: 0 }, Norte: { anuncios: 0, revendas: 0 } }, marcas: [{ marca: 'Volvo', valor: 'Volvo', anuncios: 322, n: 322 }, { marca: 'Scania', valor: 'Scania', anuncios: 255, n: 255 }, { marca: 'DAF', valor: 'DAF', anuncios: 193, n: 193 }], modelos: [{ marca: 'Volvo', modelo: 'FH 540', valor: 'FH 540', anuncios: 42, n: 42 }, { marca: 'Scania', modelo: 'R 450', valor: 'R 450', anuncios: 36, n: 36 }, { marca: 'DAF', modelo: 'XF 530', valor: 'XF 530', anuncios: 28, n: 28 }], anos: [{ ano: 2020, anuncios: 36 }, { ano: 2021, anuncios: 42 }, { ano: 2022, anuncios: 28 }], periodos: ['7d', '30d', '90d'], categorias: [{ valor: 'caminhoes', n: 1284 }], resumo: { marcas: 3, modelos: 18, precos: 31, referencia: 'FIPE DEMO', referencia_codigo: 'E001-001' } };
const mercadoModelos = [{ id: 'modelo-volvo-fh540-2021', rotulo: 'Volvo FH 540 · 2021', marca: 'Volvo', modelo: 'FH 540', ano: 2021, anuncios: 11, lojistas: 8, precos: { mediana: 498000, p25: 475000, p75: 520000, amostra_qualificada: 9, confianca: 'media' }, movimento_pct: 2.4, regioes: [{ regiao: 'Sul', anuncios: 7 }, { regiao: 'Sudeste', anuncios: 4 }], serie: [{ preco_medio: 492000, ofertas: 9 }, { preco_medio: 498000, ofertas: 11 }] }, { id: 'modelo-scania-r450-2020', rotulo: 'Scania R 450 · 2020', marca: 'Scania', modelo: 'R 450', ano: 2020, anuncios: 9, lojistas: 6, precos: { mediana: 425000, p25: 401000, p75: 449000, amostra_qualificada: 7, confianca: 'media' }, movimento_pct: -1.1, regioes: [{ regiao: 'Sul', anuncios: 3 }, { regiao: 'Sudeste', anuncios: 6 }], serie: [{ preco_medio: 429000, ofertas: 8 }, { preco_medio: 425000, ofertas: 9 }] }, { id: 'modelo-daf-xf530-2022', rotulo: 'DAF XF 530 · 2022', marca: 'DAF', modelo: 'XF 530', ano: 2022, anuncios: 7, lojistas: 5, precos: { mediana: 530000, p25: 510000, p75: 552000, amostra_qualificada: 5, confianca: 'baixa' }, movimento_pct: 0.6, regioes: [{ regiao: 'Sul', anuncios: 5 }, { regiao: 'Sudeste', anuncios: 2 }], serie: [{ preco_medio: 526000, ofertas: 6 }, { preco_medio: 530000, ofertas: 7 }] }];
const oportunidadeRegional = { melhor_uf: 'PR', historico_eventos: { disponivel: true, cobertura_dias: 120 }, nota: 'Índice comparativo entre as UFs deste modelo e ano. Saída observada não é venda; UFs sem amostra ou histórico suficiente não recebem selo de oportunidade.', regioes: [
  { uf: 'PR', comparaveis: 36, amostra_total: 38, revendas: 8, preco_mediano: 498000, saidas_observadas: 14, mediana_dias_saida: 40, cobertura_dias: 120, avaliacao: { pontuacao: 71.4, publicavel: true, confianca: 'alta', motivo_confianca: 'amostra ampla e cobertura contínua', componentes: { movimento: { indice: 80, peso: 30, contribuicao: 24 }, concorrencia: { indice: 50, peso: 20, contribuicao: 10 }, tempo_saida: { indice: 60, peso: 20, contribuicao: 12 }, preco: { indice: 90, peso: 15, contribuicao: 13.5 }, qualidade: { indice: 80, peso: 15, contribuicao: 12 } } } },
  { uf: 'GO', comparaveis: 12, amostra_total: 13, revendas: 4, preco_mediano: 470000, saidas_observadas: 4, mediana_dias_saida: 27.5, cobertura_dias: 120, avaliacao: { pontuacao: 63.2, publicavel: true, confianca: 'media', motivo_confianca: 'amostra suficiente com cobertura regional', componentes: { movimento: { indice: 62, peso: 30, contribuicao: 18.6 }, concorrencia: { indice: 100, peso: 20, contribuicao: 20 }, tempo_saida: { indice: 100, peso: 20, contribuicao: 20 }, preco: { indice: 94, peso: 15, contribuicao: 14.1 }, qualidade: { indice: 40, peso: 15, contribuicao: 6 } } } },
  { uf: 'SC', comparaveis: 3, amostra_total: 3, revendas: 2, preco_mediano: null, saidas_observadas: 1, mediana_dias_saida: null, cobertura_dias: 120, avaliacao: { pontuacao: 22, publicavel: false, confianca: 'insuficiente', motivo_confianca: 'menos de 5 comparáveis', componentes: { movimento: { indice: 40, peso: 30, contribuicao: 12 }, concorrencia: { indice: 0, peso: 20, contribuicao: 0 }, tempo_saida: { indice: 0, peso: 20, contribuicao: 0 }, preco: { indice: 0, peso: 15, contribuicao: 0 }, qualidade: { indice: 12, peso: 15, contribuicao: 1.8 } } } }] };
const kpis = { ufs_ativas: ['PR', 'SP', 'SC'], regioes_ativas: ['Sul', 'Sudeste'], ultima_coleta: today, revendas_monitoradas: 48, anuncios_ativos_revalidados: 1284, saidas_detectadas_mes: 37, entradas_48h: 64, saidas_48h: 21, ciclo_referencia: { janela: '30d' } };
const itemLoja = extra => ({ id: 501, referencia_interna: 'EST-DEMO-001', titulo: 'Volvo FH 540 2021', placa: 'AAA0A00', marca: 'Volvo', modelo: 'FH 540', ano: 2021, preco_anunciado: 515000, preco_fipe: 505000, marca_fipe: 'Volvo', modelo_fipe: 'FH 540', ano_fipe: '2021-1', cidade: 'Curitiba', uf: 'PR', dias_estoque: 18, status: 'estoque', usar_comparativo: 1, mercado_amostra_suficiente: true, mercado_amostra_total: 14, preco_mediana_mercado: 480000, menor_preco_mercado: 452000, anuncios_comparaveis: 11, anuncios_ativos: 11, mercado_confianca: 'media', mercado_escopo: 'Brasil', origem: 'manual', ...extra });
// Um veículo por estado da Minha Loja: acima do mercado, competitivo, sem amostra e fora da base comparativa.
const estoque = [itemLoja({}),
  itemLoja({ id: 502, referencia_interna: 'EST-DEMO-002', titulo: 'Scania R450 2019', placa: 'BBB1B11', marca: 'Scania', modelo: 'R450', ano: 2019, preco_anunciado: 452000, preco_fipe: 470000, preco_mediana_mercado: 455000, menor_preco_mercado: 430000, dias_estoque: 41, anuncios_comparaveis: 32, mercado_amostra_total: 35, mercado_confianca: 'alta', origem: 'xml' }),
  itemLoja({ id: 503, referencia_interna: 'EST-DEMO-003', titulo: 'Mercedes-Benz Actros 2651 2015', placa: 'CCC2C22', marca: 'Mercedes-Benz', modelo: 'Actros 2651', ano: 2015, preco_anunciado: 330000, preco_fipe: null, mercado_amostra_suficiente: false, preco_mediana_mercado: null, menor_preco_mercado: null, anuncios_comparaveis: 3, mercado_amostra_total: 3, mercado_confianca: 'insuficiente', dias_estoque: 77, uf: 'SC', cidade: 'Joinville' }),
  itemLoja({ id: 504, referencia_interna: 'EST-DEMO-004', titulo: 'DAF XF 480 2020', placa: 'DDD3D33', marca: 'DAF', modelo: 'XF 480', ano: 2020, preco_anunciado: 470000, usar_comparativo: 0, dias_estoque: 9 })];
const fipes = [{ id: 'E001-001', marca: 'Volvo', modelo: 'FH 540', ano: 2021, codigo_fipe: 'E001-001', preco_fipe: 505000, mes_referencia: '2026-09', anuncios_comparaveis: 11, mercado_amostra_suficiente: 1, preco_mediano_mercado: 498000, mercado_confianca: 'media', abaixo_fipe: 7, ufs: ['PR', 'SP'] }, { id: 'E002-002', marca: 'Scania', modelo: 'R 450', ano: 2020, codigo_fipe: 'E002-002', preco_fipe: 431000, mes_referencia: '2026-09', anuncios_comparaveis: 9, mercado_amostra_suficiente: 1, preco_mediano_mercado: 425000, mercado_confianca: 'media', abaixo_fipe: 4, ufs: ['SP'] }];
export const DEMO_SESSION = { autenticado: true, csrf: 'demo-csrf-token', usuario: { id: 1, nome: 'Pessoa Demo', email: 'demo@example.invalid', papel: 'demonstração' } };
const jsonResponse = (payload, status = 200) => ({ ok: status >= 200 && status < 300, status, json: async () => payload });
const endpoint = input => { const u = new URL(String(input), 'https://demo.invalid'); return { path: u.pathname.split('/').pop(), params: u.searchParams }; };
const anunciosPayload = (params) => ({ anuncios: baseAnuncios, total: baseAnuncios.length, pagina: 1, por_pagina: Number(params.get('limit') || 40), facetas, escopo: { periodo: params.get('periodo') || '30d', uf: params.get('uf') || 'todas' }, _meta: { demo: true, atualizado_em: today, cobertura: 'fixture local' } });
export function demoGet(input) {
  const { path: caminho, params } = endpoint(input);
  const path = caminho === 'hoje_stats.php.novo' ? 'hoje_stats.php' : caminho;
  // Simula um servidor ainda sem os campos/endpoints novos da tela Hoje (localStorage 'oper-demo-api-antiga' = '1').
  const apiAntiga = typeof localStorage !== 'undefined' && localStorage.getItem('oper-demo-api-antiga') === '1';
  if (apiAntiga && caminho === 'frescor_coleta.php') return { erro: 'Nao encontrado.', codigo: 'NAO_ENCONTRADO' };
  if (apiAntiga && caminho === 'hoje_stats.php') { const antigo = { ...demoGet('hoje_stats.php.novo') }; ['feed', 'ufs_saidas', 'insights', 'atualizado_em', 'parciais_indisponiveis'].forEach(chave => delete antigo[chave]); return antigo; }
  if (path === 'kpis.php') return kpis;
  if (path === 'hoje_stats.php') return { kpis, feed: [{ tipo: 'novo', anuncio_id: 101, url: 'https://exemplo.invalid/101', marca: 'Volvo', modelo: 'FH 540', ano: 2021, cidade: 'Curitiba', uf: 'PR', preco: 489900, quando: '2026-09-23 09:12:00' }, { tipo: 'preco', anuncio_id: 102, url: 'https://exemplo.invalid/102', marca: 'Scania', modelo: 'R 450', ano: 2020, cidade: 'Londrina', uf: 'PR', preco_anterior: 432000, preco_novo: 418000, variacao_pct: -3.2, quando: '2026-09-23 00:00:00' }, { tipo: 'saida', anuncio_id: 103, url: 'https://exemplo.invalid/103', marca: 'DAF', modelo: 'XF 530', ano: 2022, cidade: 'Campinas', uf: 'SP', quando: '2026-09-22 16:40:00' }, { tipo: 'verificacao', anuncio_id: 104, url: null, marca: 'Iveco', modelo: 'S-Way', ano: 2022, cidade: 'Joinville', uf: 'SC', quando: '2026-09-22 07:05:00' }], ufs_saidas: [{ uf: 'PR', saidas: 21, ativos: 422 }, { uf: 'SP', saidas: 9, ativos: 581 }, { uf: 'SC', saidas: 7, ativos: 281 }], insights: [{ id: 'saidas-uf', tipo: 'saidas', titulo: 'PR concentra as saídas observadas', texto: '21 dos 37 anúncios que saíram do radar em 30 dias eram de PR. Saída observada não comprova venda.', evidencia: { recorte: 'PR · caminhões e implementos', periodo: 'Últimos 30 dias', valor: '21 saídas', base: '37 saídas no total', amostra: '422 anúncios ativos', confianca: 'alta', atualizacao: '23/09/2026 12:00', explicacao: 'Anúncio ausente em verificações consecutivas do portal. Não confirma venda.' }, acao: { rotulo: 'Ver mercado da região', pagina: 'mercado', contexto: { uf: 'PR' } } }, { id: 'abaixo-fipe', tipo: 'preco', titulo: 'Volvo FH 540 2021 anunciado abaixo da FIPE', texto: 'A mediana qualificada (R$ 498.000) está 1,4% abaixo da FIPE (R$ 505.000). Pode indicar oportunidade de compra; confira estado e versão.', evidencia: { recorte: 'Volvo FH 540 2021 · todas as UFs', periodo: 'Estoque ativo', valor: 'R$ 498.000', base: 'FIPE R$ 505.000', amostra: '9 preços válidos · 6 revendas', confianca: 'baixa', atualizacao: '23/09/2026 12:00', explicacao: 'Mediana qualificada (sem valores extremos ou inválidos), não média bruta.' }, acao: { rotulo: 'Ver modelo no mercado', pagina: 'mercado', contexto: { marca: 'Volvo', modelo: 'FH 540', ano: 2021 } } }], atualizado_em: '2026-09-23 12:00:00', parciais_indisponiveis: [], top_modelos: [{ modelo: 'Volvo FH 540 2021', n: 42, preco_medio: 492000 }], regioes_saidas: [{ cidade: 'Curitiba', uf: 'PR', n: 14 }], top_lojas_novos: [{ nome: 'Rota Exemplo Caminhoes', n: 8 }], top_lojas_saidas: [{ nome: 'Patio Demonstracao', n: 3 }], regioes: [{ uf: 'PR', saidas: 14 }, { uf: 'SP', saidas: 11 }], modelos: [{ marca: 'Volvo', modelo: 'FH 540', ano: 2021, anuncios: 42, preco_mediano: 492000 }] };
  if (path === 'frescor_coleta.php') return { limite_horas: 24, resumo: { ufs: 3, severidade: 'alta', em_dia: 1, parcial: 1, atrasada: 1, sem_coleta: 0 }, itens: [{ uf: 'SC', ultima_coleta: '2026-09-21 19:00:00', horas: 41, revendas: 9, revendas_coletadas_24h: 0, cobertura_pct: 0, status: 'atrasada' }, { uf: 'SP', ultima_coleta: '2026-09-23 07:05:00', horas: 5, revendas: 15, revendas_coletadas_24h: 8, cobertura_pct: 53, status: 'parcial' }, { uf: 'PR', ultima_coleta: '2026-09-23 07:05:00', horas: 5, revendas: 18, revendas_coletadas_24h: 18, cobertura_pct: 100, status: 'em_dia' }], atualizado_em: '2026-09-23 12:00:00' };
  if (path === 'facetas.php' || path === 'comparador.php' && params.get('facetas')) return facetas;
  if (path === 'anuncios.php') return anunciosPayload(params);
  if (path === 'mercado_painel.php') { const selecionado = mercadoModelos.find(item => (!params.get('marca') || item.marca === params.get('marca')) && (!params.get('modelo') || item.modelo === params.get('modelo')) && (!params.get('ano') || String(item.ano) === params.get('ano'))) || mercadoModelos[0]; return { resumo: { anuncios: 1284, lojistas: 48, cidades: 22, ufs: 3, ticket_mediano: 428000, amostra_qualificada: 310, confianca: 'alta', desvio_fipe_mediano_pct: -1.4, desvio_fipe_amostra: 37, desvio_fipe_confianca: 'media', entradas_periodo: 64, saidas_periodo: 21 }, geografia: { ufs: [{ uf: 'PR', anuncios: 422 }, { uf: 'SP', anuncios: 581 }, { uf: 'SC', anuncios: 281 }], cidades: [{ cidade: 'Curitiba', anuncios: 322 }] }, modelos: mercadoModelos, selecionado: apiAntiga ? selecionado : { ...selecionado, oportunidade_regional: oportunidadeRegional }, fonte: { atualizado_em: '2026-09-23 12:00:00', nota: 'Preços são anunciados. Saída detectada não comprova venda.' }, anuncios: baseAnuncios, escopo: { uf: params.get('uf') || 'todas', regiao: params.get('regiao') || 'todas', periodo: params.get('periodo') || '30d' } }; }
  if (path === 'comparador.php') return { lado_a: { rotulo: 'Volvo FH 540 · 2021', preco_mediano: 498000, ofertas: 11 }, lado_b: { rotulo: 'Scania R 450 · 2020', preco_mediano: 425000, ofertas: 9 }, comparaveis: baseAnuncios, resultado: baseAnuncios, _meta: { demo: true } };
  if (path === 'lojistas.php') return { lojistas: [{ id: 11, nome: 'Rota Exemplo Caminhoes', cidade: 'Curitiba', uf: 'PR', ativos: 18, saidas_30d: 3, reducoes_30d: 2, idade_media_estoque: 47, idade_observada_confiavel: true, desvio_fipe_mediano_pct: -2.4, desvio_fipe_amostra: 9, desvio_fipe_confianca: 'baixa' }, { id: 12, nome: 'Patio Demonstracao', cidade: 'Campinas', uf: 'SP', ativos: 14, saidas_30d: 2, reducoes_30d: 1, idade_media_estoque: 32, idade_observada_confiavel: true, desvio_fipe_mediano_pct: null, desvio_fipe_amostra: 3, desvio_fipe_confianca: 'insuficiente' }], total: 2, facetas };
  if (path === 'lojista_detalhe.php') return { lojista: { id: Number(params.get('id') || 11), nome: 'Rota Exemplo Caminhoes', cidade: 'Curitiba', uf: 'PR' }, resumo: { ativos: 18, saidas_observadas: 7, saidas_30d: 3, reducoes_30d: 2, idade_media_estoque: 47, idade_observada_confiavel: true, desvio_fipe_mediano_pct: -2.4, desvio_fipe_amostra: 9, desvio_fipe_confianca: 'baixa' }, confianca: { nivel: 'media', motivo: 'Historico com cobertura parcial.' }, estoque_ativo: baseAnuncios.map((a, i) => ({ anuncio_id: i + 1, titulo: a.titulo, preco: a.preco, dias_observados: 30 + i * 8, modelo: a.modelo, url: a.url })), saidas_observadas: [{ evento_id: 41, titulo: baseAnuncios[0].titulo, preco_saida: 489900, dias_observados: 42, reapareceu: false, url: baseAnuncios[0].url }], nota: 'Saida observada nao comprova venda.' };
  if (path === 'fipe_status.php') return { disponivel: true, provedor: 'fixture local', atualizado_em: today, cobertura: 'catalogo demonstrativo' };
  if (path === 'placa_consulta.php') { if (params.get('modo') === 'status') return { disponivel: true, configurado: false, modo: 'demo' }; return { placa: params.get('placa'), veiculo: { marca: 'Volvo', modelo: 'FH 540', ano_modelo: 2021, cidade: 'Curitiba', uf: 'PR' }, fipes, mercado: fipes[0] }; }
  if (path === 'fipe_consulta.php') return { itens: fipes, fipes, total: fipes.length, resultado: fipes[0], consultado_em: today };
  if (path === 'insights.php') return { kpis: { fipe: { vinculados: 8, abaixo_fipe: 3, desvio_mediano_pct: -1.6 }, cobertura: { ufs: 3 } }, por_cidade: [{ cidade: 'Curitiba', uf: 'PR', anuncios: 322 }], lojistas: [{ revenda: 'Rota Exemplo Caminhoes', uf: 'PR', anuncios: 18 }], atualizado_em: today };
  if (path === 'analista_status.php') return { disponivel: true, configurado: true, modo: 'demo', aviso: 'Resposta local ficticia; sem contexto de backend.' };
  if (path === 'auth.php') return DEMO_SESSION;
  if (path === 'anuncio_detalhe.php') return { anuncio: baseAnuncios[0], historico: [{ data: '2026-09-21', preco: 499900 }, { data: '2026-09-23', preco: 489900 }], similares: baseAnuncios };
  if (path === 'minha_loja.php' || path === 'minha_loja_detalhe.php') return path === 'minha_loja.php' ? { itens: estoque, total: estoque.length } : { item: estoque[0], mercado: fipes[0] };
  return { demo: true, _meta: { demo: true, endpoint: path, atualizado_em: today } };
}
export function demoPost(input) {
  const { path } = endpoint(input);
  if (path === 'auth.php') return path;
  if (path === 'analista.php') return { resposta: 'Leitura demonstrativa: compare o preço anunciado à FIPE e à mediana qualificada antes de decidir.', fontes: ['fixture local'], demo: true };
  if (path === 'minha_loja_xml.php') return { analise: { resumo: { validos: 1, sem_id_estavel: 0, novos: 1, ausentes: 0 }, itens: estoque }, resultado: { importados: 1, atualizados: 0, ausentes_marcados_vendidos: 0 }, demo: true };
  if (path === 'minha_loja.php') return { item: estoque[0], itens: estoque, salvo: true, demo: true };
  return { ok: true, demo: true, endpoint: path, mensagem: 'Mutacao simulada localmente.' };
}
export const DEMO_MODE = typeof import.meta.env !== 'undefined' && import.meta.env.VITE_DEMO === '1';
export function demoFetch(input, options = {}) { return Promise.resolve(jsonResponse(options.method && options.method !== 'GET' ? demoPost(input, options) : demoGet(input))); }
