const today = '2026-09-23T12:00:00-03:00';
const baseAnuncios = [
  { anuncio_id: 101, anuncio_portal_id: 'DEMO-001', titulo: 'Volvo FH 540 6x4 2021', tipo: 'caminhao', marca: 'Volvo', modelo: 'FH 540', ano_fabricacao: 2021, ano_modelo: 2021, preco: 489900, preco_fipe: 505000, codigo_fipe: 'E001-001', fipe_match_status: 'vinculado', fipe_match_confianca: 'alta', fipe_vinculo_origem: 'automatico', cidade: 'Curitiba', uf: 'PR', regiao: 'Sul', revenda_id: 11, revenda: 'Rota Exemplo Caminhoes', quilometragem: 312000, primeira_vez_visto: '2026-08-24', ultima_vez_ativo: today, anuncios_comparaveis: 11, preco_mediano_mercado: 498000, preco_p25_mercado: 475000, preco_p75_mercado: 520000, mercado_confianca: 'media', mercado_amostra_suficiente: 1, preco_qualidade_status: 'valido', status: 'ativo' },
  { anuncio_id: 102, anuncio_portal_id: 'DEMO-002', titulo: 'Scania R 450 2020', tipo: 'caminhao', marca: 'Scania', modelo: 'R 450', ano_fabricacao: 2020, ano_modelo: 2020, preco: 418000, preco_fipe: 431000, codigo_fipe: 'E002-002', fipe_match_status: 'vinculado', fipe_match_confianca: 'media', cidade: 'Campinas', uf: 'SP', regiao: 'Sudeste', revenda_id: 12, revenda: 'Patio Demonstracao', quilometragem: 365000, primeira_vez_visto: '2026-07-15', ultima_vez_ativo: today, anuncios_comparaveis: 9, preco_mediano_mercado: 425000, preco_p25_mercado: 401000, preco_p75_mercado: 449000, mercado_confianca: 'media', mercado_amostra_suficiente: 1, preco_qualidade_status: 'valido', status: 'ativo' },
  { anuncio_id: 103, anuncio_portal_id: 'DEMO-003', titulo: 'DAF XF 530 2022', tipo: 'caminhao', marca: 'DAF', modelo: 'XF 530', ano_fabricacao: 2022, ano_modelo: 2022, preco: 536000, preco_fipe: 521000, codigo_fipe: 'E003-003', fipe_match_status: 'vinculado', fipe_match_confianca: 'baixa', cidade: 'Londrina', uf: 'PR', regiao: 'Sul', revenda_id: 13, revenda: 'Caminhoes Modelo', quilometragem: 198000, primeira_vez_visto: '2026-08-01', ultima_vez_ativo: today, anuncios_comparaveis: 7, preco_mediano_mercado: 530000, mercado_confianca: 'baixa', mercado_amostra_suficiente: 1, preco_qualidade_status: 'valido', status: 'ativo' }
];
const ufs = { PR: { regiao: 'Sul', anuncios: 422, revendas: 18, cidades: [{ cidade: 'Curitiba', n: 322, uf: 'PR' }, { cidade: 'Londrina', n: 100, uf: 'PR' }], lojistas: [{ id: 11, nome: 'Rota Exemplo Caminhoes', n: 18 }] }, SP: { regiao: 'Sudeste', anuncios: 391, revendas: 15, cidades: [{ cidade: 'Campinas', n: 255, uf: 'SP' }, { cidade: 'Sao Paulo', n: 136, uf: 'SP' }], lojistas: [{ id: 12, nome: 'Patio Demonstracao', n: 14 }] }, SC: { regiao: 'Sul', anuncios: 281, revendas: 9, cidades: [{ cidade: 'Joinville', n: 126, uf: 'SC' }], lojistas: [] } };
const facetas = { total_geral: 1284, ufs, por_uf: { PR: 422, SP: 391, SC: 281 }, revendas_por_uf: { PR: 18, SP: 15, SC: 9 }, regioes: ['Sul', 'Sudeste'], marcas: [{ valor: 'Volvo', n: 322 }, { valor: 'Scania', n: 255 }, { valor: 'DAF', n: 193 }], modelos: [{ valor: 'FH 540', n: 42 }, { valor: 'R 450', n: 36 }, { valor: 'XF 530', n: 28 }], anos: [2020, 2021, 2022], periodos: ['7d', '30d', '90d'], categorias: [{ valor: 'caminhoes', n: 1284 }], resumo: { marcas: 3, modelos: 18, precos: 31, referencia: 'FIPE DEMO', referencia_codigo: 'E001-001' } };
const kpis = { ufs_ativas: ['PR', 'SP', 'SC'], regioes_ativas: ['Sul', 'Sudeste'], ultima_coleta: today, revendas_monitoradas: 48, anuncios_ativos_revalidados: 1284, saidas_detectadas_mes: 37, entradas_48h: 64, saidas_48h: 21, ciclo_referencia: { janela: '30d' } };
const estoque = [{ id: 501, referencia_interna: 'EST-DEMO-001', titulo: 'Volvo FH 540 2021', placa: 'AAA0A00', marca: 'Volvo', modelo: 'FH 540', ano: 2021, preco_anunciado: 515000, preco_fipe: 505000, marca_fipe: 'Volvo', modelo_fipe: 'FH 540', ano_fipe: 2021, cidade: 'Curitiba', uf: 'PR', dias_estoque: 18, status: 'estoque', usar_comparativo: 1, mercado_amostra_suficiente: 1, preco_mediano_mercado: 498000, anuncios_ativos: 11, mercado_confianca: 'media', origem: 'manual' }];
const fipes = [{ id: 'E001-001', marca: 'Volvo', modelo: 'FH 540', ano: 2021, codigo_fipe: 'E001-001', preco_fipe: 505000, mes_referencia: '2026-09', anuncios_comparaveis: 11, mercado_amostra_suficiente: 1, preco_mediano_mercado: 498000, mercado_confianca: 'media', abaixo_fipe: 7, ufs: ['PR', 'SP'] }, { id: 'E002-002', marca: 'Scania', modelo: 'R 450', ano: 2020, codigo_fipe: 'E002-002', preco_fipe: 431000, mes_referencia: '2026-09', anuncios_comparaveis: 9, mercado_amostra_suficiente: 1, preco_mediano_mercado: 425000, mercado_confianca: 'media', abaixo_fipe: 4, ufs: ['SP'] }];
export const DEMO_SESSION = { autenticado: true, csrf: 'demo-csrf-token', usuario: { id: 1, nome: 'Pessoa Demo', email: 'demo@example.invalid', papel: 'demonstração' } };
const jsonResponse = (payload, status = 200) => ({ ok: status >= 200 && status < 300, status, json: async () => payload });
const endpoint = input => { const u = new URL(String(input), 'https://demo.invalid'); return { path: u.pathname.split('/').pop(), params: u.searchParams }; };
const anunciosPayload = (params) => ({ anuncios: baseAnuncios, total: baseAnuncios.length, pagina: 1, por_pagina: Number(params.get('limit') || 40), facetas, escopo: { periodo: params.get('periodo') || '30d', uf: params.get('uf') || 'todas' }, _meta: { demo: true, atualizado_em: today, cobertura: 'fixture local' } });
export function demoGet(input) {
  const { path, params } = endpoint(input);
  if (path === 'kpis.php') return kpis;
  if (path === 'hoje_stats.php') return { kpis, feed: baseAnuncios, top_modelos: [{ modelo: 'Volvo FH 540 2021', n: 42, preco_medio: 492000 }], regioes_saidas: [{ cidade: 'Curitiba', uf: 'PR', n: 14 }], top_lojas_novos: [{ nome: 'Rota Exemplo Caminhoes', n: 8 }], top_lojas_saidas: [{ nome: 'Patio Demonstracao', n: 3 }], regioes: [{ uf: 'PR', saidas: 14 }, { uf: 'SP', saidas: 11 }], modelos: [{ marca: 'Volvo', modelo: 'FH 540', ano: 2021, anuncios: 42, preco_mediano: 492000 }] };
  if (path === 'facetas.php' || path === 'comparador.php' && params.get('facetas')) return facetas;
  if (path === 'anuncios.php') return anunciosPayload(params);
  if (path === 'mercado_painel.php') return { resumo: { anuncios: 1284, lojistas: 48, cidades: 22, ufs: 3, preco_mediano: 428000 }, geografia: { ufs: [{ uf: 'PR', anuncios: 422 }, { uf: 'SP', anuncios: 391 }], cidades: [{ cidade: 'Curitiba', anuncios: 322 }] }, modelos: [{ marca: 'Volvo', modelo: 'FH 540', ano: 2021, anuncios: 42, preco_mediano: 489900 }], selecionado: fipes[0], anuncios: baseAnuncios, escopo: { uf: params.get('uf') || 'todas', periodo: params.get('periodo') || '30d' } };
  if (path === 'comparador.php') return { lado_a: { rotulo: 'Volvo FH 540 · 2021', preco_mediano: 498000, ofertas: 11 }, lado_b: { rotulo: 'Scania R 450 · 2020', preco_mediano: 425000, ofertas: 9 }, comparaveis: baseAnuncios, resultado: baseAnuncios, _meta: { demo: true } };
  if (path === 'lojistas.php') return { lojistas: [{ id: 11, nome: 'Rota Exemplo Caminhoes', cidade: 'Curitiba', uf: 'PR', anuncios: 18, saidas: 3, reducoes: 2 }, { id: 12, nome: 'Patio Demonstracao', cidade: 'Campinas', uf: 'SP', anuncios: 14, saidas: 2, reducoes: 1 }], total: 2, facetas };
  if (path === 'lojista_detalhe.php') return { lojista: { id: Number(params.get('id') || 11), nome: 'Rota Exemplo Caminhoes', cidade: 'Curitiba', uf: 'PR', anuncios: 18, saidas: 3 }, anuncios: baseAnuncios, eventos: [{ tipo: 'preco_caiu', data: '2026-09-21', titulo: baseAnuncios[0].titulo, anterior: 499900, atual: 489900 }] };
  if (path === 'fipe_status.php') return { disponivel: true, provedor: 'fixture local', atualizado_em: today, cobertura: 'catalogo demonstrativo' };
  if (path === 'placa_consulta.php') { if (params.get('modo') === 'status') return { disponivel: true, configurado: false, modo: 'demo' }; return { placa: params.get('placa'), veiculo: { marca: 'Volvo', modelo: 'FH 540', ano_modelo: 2021, cidade: 'Curitiba', uf: 'PR' }, fipes, mercado: fipes[0] }; }
  if (path === 'fipe_consulta.php') return { itens: fipes, fipes, total: fipes.length, resultado: fipes[0], consultado_em: today };
  if (path === 'insights.php') return { kpis: { fipe: { vinculados: 8, abaixo_fipe: 3, desvio_mediano_pct: -1.6 }, cobertura: { ufs: 3 } }, por_cidade: [{ cidade: 'Curitiba', uf: 'PR', anuncios: 322 }], lojistas: [{ revenda: 'Rota Exemplo Caminhoes', uf: 'PR', anuncios: 18 }], atualizado_em: today };
  if (path === 'analista_status.php') return { disponivel: true, configurado: true, modo: 'demo', aviso: 'Resposta local ficticia; sem contexto de backend.' };
  if (path === 'auth.php') return DEMO_SESSION;
  if (path === 'anuncio_detalhe.php') return { anuncio: baseAnuncios[0], historico: [{ data: '2026-09-21', preco: 499900 }, { data: '2026-09-23', preco: 489900 }], similares: baseAnuncios };
  if (path === 'minha_loja.php' || path === 'minha_loja_detalhe.php') return path === 'minha_loja.php' ? { itens: estoque, total: estoque.length } : { item: estoque[0], mercado: fipes[0] };
  return { demo: true, _meta: { demo: true, endpoint: path, atualizado_em: today } };
}
export function demoPost(input) {
  const { path } = endpoint(input);
  if (path === 'auth.php') return path;
  if (path === 'analista.php') return { resposta: 'Leitura demonstrativa: compare o preço anunciado à FIPE e à mediana qualificada antes de decidir.', fontes: ['fixture local'], demo: true };
  if (path === 'minha_loja_xml.php') return { analise: { resumo: { validos: 1, sem_id_estavel: 0, novos: 1, ausentes: 0 }, itens: estoque }, resultado: { importados: 1, atualizados: 0, ausentes_marcados_vendidos: 0 }, demo: true };
  if (path === 'minha_loja.php') return { item: estoque[0], itens: estoque, salvo: true, demo: true };
  return { ok: true, demo: true, endpoint: path, mensagem: 'Mutacao simulada localmente.' };
}
export const DEMO_MODE = typeof import.meta.env !== 'undefined' && import.meta.env.VITE_DEMO === '1';
export function demoFetch(input, options = {}) { return Promise.resolve(jsonResponse(options.method && options.method !== 'GET' ? demoPost(input, options) : demoGet(input))); }
